name: "Newman Tests"
on: [push, pull_request]

jobs:
build:
runs-on: ubunta-latest
container:
image: postman/newman
steps:
- name: Checkout
  uses: actions/checkout@v2
  
  - name: Run API Tests
    run: newman run RestfullBookerBVT.postman_collection.json
  
